Veamos como creo otro arreglo diferente al original, y al modificarlo se modifica tambien el original.

In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
trozo_arr = arr[:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Para solucionar esto, exite el comando copy() 

In [10]:
arr_copy = arr.copy()

In [11]:
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [13]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])