In [2]:
import numpy as np

La manera tradicional de creacion de listas puede ser como:

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

pero numpy tambien nos permite la creadcion de arrays desde cero, aprovechando todos los beneficos del modulo.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((10,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

Para los amantes del algebra, tambien es posible:

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Para generar valores aleatorios:

In [13]:
np.random.rand()

0.02642715470995749

In [14]:
np.random.rand(4)

array([0.73521164, 0.42665007, 0.6835924 , 0.91979087])

In [15]:
np.random.rand(4,4)

array([[0.98615344, 0.21618096, 0.5393106 , 0.71002452],
       [0.06284275, 0.31775096, 0.4540322 , 0.33945079],
       [0.56165348, 0.95372509, 0.37292116, 0.81746747],
       [0.10807821, 0.55795342, 0.83474178, 0.20491419]])

Para generar un numero aletario entre un rango:

In [22]:
np.random.randint(1,15)

8

In [23]:
np.random.randint(1,100, (10,10))

array([[39, 72, 90,  1, 10,  1, 72, 22,  3, 96],
       [56, 54, 86, 36, 47, 52, 17, 39, 32, 87],
       [79, 41, 44,  4, 64, 55, 68, 35, 50, 38],
       [88, 75, 58, 82, 54, 83, 22, 73, 55, 28],
       [52, 48, 89, 86, 32, 38, 78, 54, 78, 39],
       [82, 67,  2, 16, 39, 61, 84, 50, 88, 45],
       [53, 95, 70, 43, 27, 57, 21, 79, 81, 34],
       [13, 35, 95, 70,  6, 48, 21, 55,  1, 45],
       [ 8, 11, 41, 54, 49, 93, 95, 68, 81, 89],
       [92, 77, 75, 41, 61, 70, 84, 55, 77, 52]])