In [2]:
import numpy as np 


Creamos una array y una matriz:

In [48]:
arr = np.random.randint(1,20,10)
arr

array([13, 16, 13,  1,  5,  5,  4,  1, 14,  2])

In [49]:
matriz = arr.reshape(2,5)
matriz

array([[13, 16, 13,  1,  5],
       [ 5,  4,  1, 14,  2]])

Funcion Max():

In [50]:
arr.max()

16

In [51]:
matriz.max()

16

Para determinar el maximo por columanas

In [52]:
matriz.max(0)

array([13, 16, 13, 14,  5])

para determinar el maximo por filas

In [53]:
matriz.max(1)

array([16, 14])

Como saber cual es el indice de nuestros valor maximo?

In [54]:
arr.argmax()

1

In [55]:
matriz.argmax(0)

array([0, 0, 0, 1, 0])

In [56]:
matriz.argmax(1)

array([1, 3])

tambien exite la funcion min ():
Podemos realizar todo lo anterior.


In [57]:
arr.min()


1

In [58]:
matriz.min(0)

array([5, 4, 1, 1, 2])

In [59]:
matriz.argmin(1)

array([3, 2])

Como saber cuanta distancia ahi desde el valor minimo al valor maximo ? funcion ptp() (de pico a pico)

In [60]:
arr

array([13, 16, 13,  1,  5,  5,  4,  1, 14,  2])

In [61]:
arr.ptp()

15

In [62]:
matriz

array([[13, 16, 13,  1,  5],
       [ 5,  4,  1, 14,  2]])

In [63]:
matriz.ptp(0)

array([ 8, 12, 12, 13,  3])

In [64]:
matriz.ptp(1)

array([15, 13])

Organizamos el arr y sacamos percentiles:

In [67]:
arr

array([13, 16, 13,  1,  5,  5,  4,  1, 14,  2])

In [73]:
arr.sort()
arr

array([ 1,  1,  2,  4,  5,  5, 13, 13, 14, 16])

In [74]:
np.percentile(arr,50)

5.0

In [75]:
np.percentile(arr,0)

1.0

In [76]:
np.percentile(arr,100)

16.0

Mediana y desviacion estandar, varianza, media

In [78]:
np.median(arr)

5.0

In [79]:
np.median(matriz, 0)

array([ 3. ,  7. ,  7.5,  9. , 10.5])

In [80]:
np.median(matriz, 1)

array([ 2., 13.])

In [83]:
np.std(arr)**2

31.439999999999994

In [82]:
np.var(arr)

31.439999999999998

In [84]:
np.mean(arr)

7.4

In [85]:
np.mean(matriz , 0)

array([ 3. ,  7. ,  7.5,  9. , 10.5])

Concatenacion:


In [110]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [111]:
np.concatenate((a,b),axis = 0)

ValueError: ignored

In [112]:
a.ndim

2

In [113]:
b.ndim

1

In [114]:
b = np.expand_dims(b,axis=0)


In [115]:
b.ndim

2

In [116]:
np.concatenate((a,b),axis= 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [117]:
np.concatenate((a,b),axis=1)

ValueError: ignored

In [118]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])