In [5]:
import numpy as np 

In [1]:
lista = [1,2]
lista

[1, 2]

In [2]:
lista * 2

[1, 2, 1, 2]

In [10]:
arr= np.arange(0,10)
arr2 = arr.copy()
print(arr,arr2)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9]


Operaciones

In [11]:
arr2* 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
1/arr2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr2**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Con matriz

In [19]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
matriz2=matriz.copy()

In [21]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [22]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [23]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

producto punto

In [25]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [26]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])