In [2]:
import numpy as np 

In [6]:
arr = np.random.randint(1,10 ,(3,2))
print(arr)

[[9 2]
 [8 8]
 [3 2]]


cuantas cantidades tendo por cada dimencion:

In [7]:
arr.shape

(3, 2)

para reacomodar el arreglo es posible:

In [8]:
arr.reshape(1,6)

array([[9, 2, 8, 8, 3, 2]])

In [9]:
arr.reshape(2,3)

array([[9, 2, 8],
       [8, 3, 2]])

otra manera de escribit lo mismo:

In [10]:
np.reshape(arr , (1,6))

array([[9, 2, 8, 8, 3, 2]])

Como hacemos si queremos hacer el reshape pero con un orden distinto?

In [12]:
arr

array([[9, 2],
       [8, 8],
       [3, 2]])

In [13]:
np.reshape(arr, (2,3), 'C')

array([[9, 2, 8],
       [8, 3, 2]])

In [16]:
np.reshape(arr, (2,3), 'F')

array([[9, 3, 8],
       [8, 2, 2]])

In [17]:
np.reshape(arr, (2,3), 'A')

array([[9, 2, 8],
       [8, 3, 2]])