In [2]:
import numpy as np 

In [4]:
arr = np.linspace(1,10,10, dtype='int8')
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [8]:
condicion = arr > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [9]:
arr[condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [10]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[(arr > 5) ] = 99
arr

In [13]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)